-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 12:02:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Cul_d'Ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cul_d'Ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cul_d'Ampolla` DEFAULT CHARACTER SET utf8 ;
USE `Cul_d'Ampolla` ;

-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Proveïdors` (
  `idProveïdor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` INT NOT NULL,
  `fax` INT NOT NULL,
  `NIF` INT NOT NULL,
  PRIMARY KEY (`idProveïdor`),
  UNIQUE INDEX `idProveïdor_UNIQUE` (`idProveïdor` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`NIF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Empleat` (
  `idEmpleat` INT NOT NULL AUTO_INCREMENT,
  `nomEmpleat` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleat`),
  UNIQUE INDEX `idEmpleat_UNIQUE` (`idEmpleat` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Vendes` (
  `idVentes` INT NOT NULL AUTO_INCREMENT,
  `Empleat_idEmpleat` INT NOT NULL,
  PRIMARY KEY (`idVentes`),
  UNIQUE INDEX `idVentes_UNIQUE` (`idVentes` ASC) VISIBLE,
  INDEX `fk_Ventes_Empleat_idx` (`Empleat_idEmpleat` ASC) VISIBLE,
  CONSTRAINT `fk_Ventes_Empleat`
    FOREIGN KEY (`Empleat_idEmpleat`)
    REFERENCES `Cul_d'Ampolla`.`Empleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Marques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Marques` (
  `idMarca` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`),
  UNIQUE INDEX `idMarca_UNIQUE` (`idMarca` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Ulleres` (
  `idUlleres` INT NOT NULL AUTO_INCREMENT,
  `graduacióVidreDret` DECIMAL(2) NULL,
  `graduacióVidreEsquerra` DECIMAL(2) NULL,
  `colorMuntura` VARCHAR(45) NOT NULL,
  `colorVidreDret` VARCHAR(45) NOT NULL,
  `colorVidreEsquerra` VARCHAR(45) NOT NULL,
  `preu` DECIMAL NOT NULL,
  `tipusMuntura` VARCHAR(45) NOT NULL,
  `Vendes_idVentes` INT NOT NULL,
  `Marques_idMarca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUlleres`, `Marques_idMarca`),
  UNIQUE INDEX `idUlleres_UNIQUE` (`idUlleres` ASC) VISIBLE,
  INDEX `fk_Ulleres_Vendes1_idx` (`Vendes_idVentes` ASC) VISIBLE,
  INDEX `fk_Ulleres_Marques1_idx` (`Marques_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Vendes1`
    FOREIGN KEY (`Vendes_idVentes`)
    REFERENCES `Cul_d'Ampolla`.`Vendes` (`idVentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Marques1`
    FOREIGN KEY (`Marques_idMarca`)
    REFERENCES `Cul_d'Ampolla`.`Marques` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Adreça_proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Adreça_proveïdors` (
  `idAdreçaProveïdor` INT NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `número` INT NOT NULL,
  `pis` INT NOT NULL,
  `porta` INT NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codiPostal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `Proveïdors_idProveïdor` INT NOT NULL,
  PRIMARY KEY (`idAdreçaProveïdor`),
  INDEX `fk_Adreça_proveïdors_Proveïdors1_idx` (`Proveïdors_idProveïdor` ASC) VISIBLE,
  CONSTRAINT `fk_Adreça_proveïdors_Proveïdors1`
    FOREIGN KEY (`Proveïdors_idProveïdor`)
    REFERENCES `Cul_d'Ampolla`.`Proveïdors` (`idProveïdor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adreçaPostal` VARCHAR(100) NOT NULL,
  `telèfon` INT NULL,
  `email` VARCHAR(100) NULL,
  `dataRegistre` DATETIME NOT NULL,
  `recomanació` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Comandes_Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Comandes_Client` (
  `Comandes_idVentes` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`Comandes_idVentes`, `Client_idClient`),
  INDEX `fk_Comandes_has_Client_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  INDEX `fk_Comandes_has_Client_Comandes1_idx` (`Comandes_idVentes` ASC) VISIBLE,
  CONSTRAINT `fk_Comandes_has_Client_Comandes1`
    FOREIGN KEY (`Comandes_idVentes`)
    REFERENCES `Cul_d'Ampolla`.`Vendes` (`idVentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comandes_has_Client_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `Cul_d'Ampolla`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cul_d'Ampolla`.`Marques_Proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cul_d'Ampolla`.`Marques_Proveïdors` (
  `Marques_idMarca` VARCHAR(45) NOT NULL,
  `Proveïdors_idProveïdor` INT NOT NULL,
  PRIMARY KEY (`Marques_idMarca`, `Proveïdors_idProveïdor`),
  INDEX `fk_Marques_has_Proveïdors_Proveïdors1_idx` (`Proveïdors_idProveïdor` ASC) VISIBLE,
  INDEX `fk_Marques_has_Proveïdors_Marques1_idx` (`Marques_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Marques_has_Proveïdors_Marques1`
    FOREIGN KEY (`Marques_idMarca`)
    REFERENCES `Cul_d'Ampolla`.`Marques` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marques_has_Proveïdors_Proveïdors1`
    FOREIGN KEY (`Proveïdors_idProveïdor`)
    REFERENCES `Cul_d'Ampolla`.`Proveïdors` (`idProveïdor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
